type LeaderboardEntry @aws_iam @aws_api_key {
  username: String!
  timeSeconds: Int!
  userId: String!
  displayTime: String!
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelLeaderboardEntryConnection @aws_api_key @aws_iam {
  items: [LeaderboardEntry]!
  nextToken: String
}

input ModelLeaderboardEntryFilterInput {
  username: ModelStringInput
  timeSeconds: ModelIntInput
  userId: ModelStringInput
  displayTime: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelLeaderboardEntryFilterInput]
  or: [ModelLeaderboardEntryFilterInput]
  not: ModelLeaderboardEntryFilterInput
}

type Query {
  getLeaderboardEntry(id: ID!): LeaderboardEntry @aws_api_key @aws_iam
  listLeaderboardEntries(filter: ModelLeaderboardEntryFilterInput, limit: Int, nextToken: String): ModelLeaderboardEntryConnection @aws_api_key @aws_iam
}

input ModelLeaderboardEntryConditionInput {
  username: ModelStringInput
  timeSeconds: ModelIntInput
  userId: ModelStringInput
  displayTime: ModelStringInput
  and: [ModelLeaderboardEntryConditionInput]
  or: [ModelLeaderboardEntryConditionInput]
  not: ModelLeaderboardEntryConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateLeaderboardEntryInput {
  username: String!
  timeSeconds: Int!
  userId: String!
  displayTime: String!
  id: ID
}

input UpdateLeaderboardEntryInput {
  username: String
  timeSeconds: Int
  userId: String
  displayTime: String
  id: ID!
}

input DeleteLeaderboardEntryInput {
  id: ID!
}

type Mutation {
  createLeaderboardEntry(input: CreateLeaderboardEntryInput!, condition: ModelLeaderboardEntryConditionInput): LeaderboardEntry @aws_api_key @aws_iam
  updateLeaderboardEntry(input: UpdateLeaderboardEntryInput!, condition: ModelLeaderboardEntryConditionInput): LeaderboardEntry @aws_api_key @aws_iam
  deleteLeaderboardEntry(input: DeleteLeaderboardEntryInput!, condition: ModelLeaderboardEntryConditionInput): LeaderboardEntry @aws_api_key @aws_iam
}

input ModelSubscriptionLeaderboardEntryFilterInput {
  username: ModelSubscriptionStringInput
  timeSeconds: ModelSubscriptionIntInput
  userId: ModelSubscriptionStringInput
  displayTime: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionLeaderboardEntryFilterInput]
  or: [ModelSubscriptionLeaderboardEntryFilterInput]
}

type Subscription {
  onCreateLeaderboardEntry(filter: ModelSubscriptionLeaderboardEntryFilterInput): LeaderboardEntry @aws_subscribe(mutations: ["createLeaderboardEntry"]) @aws_api_key @aws_iam
  onUpdateLeaderboardEntry(filter: ModelSubscriptionLeaderboardEntryFilterInput): LeaderboardEntry @aws_subscribe(mutations: ["updateLeaderboardEntry"]) @aws_api_key @aws_iam
  onDeleteLeaderboardEntry(filter: ModelSubscriptionLeaderboardEntryFilterInput): LeaderboardEntry @aws_subscribe(mutations: ["deleteLeaderboardEntry"]) @aws_api_key @aws_iam
}
